// Copyright 2026.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "k8s-demo/exercise4/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// StaticSites returns a StaticSiteInformer.
	StaticSites() StaticSiteInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// StaticSites returns a StaticSiteInformer.
func (v *version) StaticSites() StaticSiteInformer {
	return &staticSiteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
