// Copyright 2026.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	apisstaticsitev1alpha1 "k8s-demo/exercise4/pkg/apis/staticsite/v1alpha1"
	versioned "k8s-demo/exercise4/pkg/client/clientset/versioned"
	internalinterfaces "k8s-demo/exercise4/pkg/client/informers/externalversions/internalinterfaces"
	staticsitev1alpha1 "k8s-demo/exercise4/pkg/client/listers/staticsite/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StaticSiteInformer provides access to a shared informer and lister for
// StaticSites.
type StaticSiteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() staticsitev1alpha1.StaticSiteLister
}

type staticSiteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStaticSiteInformer constructs a new informer for StaticSite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStaticSiteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStaticSiteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStaticSiteInformer constructs a new informer for StaticSite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStaticSiteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().StaticSites(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().StaticSites(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().StaticSites(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().StaticSites(namespace).Watch(ctx, options)
			},
		}, client),
		&apisstaticsitev1alpha1.StaticSite{},
		resyncPeriod,
		indexers,
	)
}

func (f *staticSiteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStaticSiteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *staticSiteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisstaticsitev1alpha1.StaticSite{}, f.defaultInformer)
}

func (f *staticSiteInformer) Lister() staticsitev1alpha1.StaticSiteLister {
	return staticsitev1alpha1.NewStaticSiteLister(f.Informer().GetIndexer())
}
