// Copyright 2026.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// StaticSiteListerExpansion allows custom methods to be added to
// StaticSiteLister.
type StaticSiteListerExpansion interface{}

// StaticSiteNamespaceListerExpansion allows custom methods to be added to
// StaticSiteNamespaceLister.
type StaticSiteNamespaceListerExpansion interface{}
