// Copyright 2026.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	staticsitev1alpha1 "k8s-demo/exercise4/pkg/apis/staticsite/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// StaticSiteLister helps list StaticSites.
// All objects returned here must be treated as read-only.
type StaticSiteLister interface {
	// List lists all StaticSites in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*staticsitev1alpha1.StaticSite, err error)
	// StaticSites returns an object that can list and get StaticSites.
	StaticSites(namespace string) StaticSiteNamespaceLister
	StaticSiteListerExpansion
}

// staticSiteLister implements the StaticSiteLister interface.
type staticSiteLister struct {
	listers.ResourceIndexer[*staticsitev1alpha1.StaticSite]
}

// NewStaticSiteLister returns a new StaticSiteLister.
func NewStaticSiteLister(indexer cache.Indexer) StaticSiteLister {
	return &staticSiteLister{listers.New[*staticsitev1alpha1.StaticSite](indexer, staticsitev1alpha1.Resource("staticsite"))}
}

// StaticSites returns an object that can list and get StaticSites.
func (s *staticSiteLister) StaticSites(namespace string) StaticSiteNamespaceLister {
	return staticSiteNamespaceLister{listers.NewNamespaced[*staticsitev1alpha1.StaticSite](s.ResourceIndexer, namespace)}
}

// StaticSiteNamespaceLister helps list and get StaticSites.
// All objects returned here must be treated as read-only.
type StaticSiteNamespaceLister interface {
	// List lists all StaticSites in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*staticsitev1alpha1.StaticSite, err error)
	// Get retrieves the StaticSite from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*staticsitev1alpha1.StaticSite, error)
	StaticSiteNamespaceListerExpansion
}

// staticSiteNamespaceLister implements the StaticSiteNamespaceLister
// interface.
type staticSiteNamespaceLister struct {
	listers.ResourceIndexer[*staticsitev1alpha1.StaticSite]
}
