// Copyright 2026.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "k8s-demo/exercise4/pkg/apis/staticsite/v1alpha1"
	staticsitev1alpha1 "k8s-demo/exercise4/pkg/client/clientset/versioned/typed/staticsite/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeStaticSites implements StaticSiteInterface
type fakeStaticSites struct {
	*gentype.FakeClientWithList[*v1alpha1.StaticSite, *v1alpha1.StaticSiteList]
	Fake *FakeDemoV1alpha1
}

func newFakeStaticSites(fake *FakeDemoV1alpha1, namespace string) staticsitev1alpha1.StaticSiteInterface {
	return &fakeStaticSites{
		gentype.NewFakeClientWithList[*v1alpha1.StaticSite, *v1alpha1.StaticSiteList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("staticsites"),
			v1alpha1.SchemeGroupVersion.WithKind("StaticSite"),
			func() *v1alpha1.StaticSite { return &v1alpha1.StaticSite{} },
			func() *v1alpha1.StaticSiteList { return &v1alpha1.StaticSiteList{} },
			func(dst, src *v1alpha1.StaticSiteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.StaticSiteList) []*v1alpha1.StaticSite { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.StaticSiteList, items []*v1alpha1.StaticSite) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
