apiVersion: v1
kind: Pod
metadata:
  name: error-pod       # Pod的名称
  labels:
    app: web           # 定义标签
spec:
  containers:
  - name: nginx-container # 容器的名称
    image: m.daocloud.io/docker.io/library/nginx:1.28  # 容器使用的镜像
    ports:
    - containerPort: 80   # 容器暴露的端口
