// Copyright 2026.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	staticsitev1alpha1 "k8s-demo/exercise4/pkg/apis/staticsite/v1alpha1"
	scheme "k8s-demo/exercise4/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// StaticSitesGetter has a method to return a StaticSiteInterface.
// A group's client should implement this interface.
type StaticSitesGetter interface {
	StaticSites(namespace string) StaticSiteInterface
}

// StaticSiteInterface has methods to work with StaticSite resources.
type StaticSiteInterface interface {
	Create(ctx context.Context, staticSite *staticsitev1alpha1.StaticSite, opts v1.CreateOptions) (*staticsitev1alpha1.StaticSite, error)
	Update(ctx context.Context, staticSite *staticsitev1alpha1.StaticSite, opts v1.UpdateOptions) (*staticsitev1alpha1.StaticSite, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, staticSite *staticsitev1alpha1.StaticSite, opts v1.UpdateOptions) (*staticsitev1alpha1.StaticSite, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*staticsitev1alpha1.StaticSite, error)
	List(ctx context.Context, opts v1.ListOptions) (*staticsitev1alpha1.StaticSiteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *staticsitev1alpha1.StaticSite, err error)
	StaticSiteExpansion
}

// staticSites implements StaticSiteInterface
type staticSites struct {
	*gentype.ClientWithList[*staticsitev1alpha1.StaticSite, *staticsitev1alpha1.StaticSiteList]
}

// newStaticSites returns a StaticSites
func newStaticSites(c *DemoV1alpha1Client, namespace string) *staticSites {
	return &staticSites{
		gentype.NewClientWithList[*staticsitev1alpha1.StaticSite, *staticsitev1alpha1.StaticSiteList](
			"staticsites",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *staticsitev1alpha1.StaticSite { return &staticsitev1alpha1.StaticSite{} },
			func() *staticsitev1alpha1.StaticSiteList { return &staticsitev1alpha1.StaticSiteList{} },
		),
	}
}
